doctrine_mongodb:
    connections:
        default:
            server: '%env(resolve:MONGODB_URI)%'
    default_database: '%env(MONGODB_DB)%'
    document_managers:
        default:
            auto_mapping: false
            mappings:
                Applications:
                    type: attribute
                    dir: '%kernel.project_dir%/src/Applications/Infrastructure/Persistence/Doctrine'
                    prefix: 'App\Applications\Infrastructure\Persistence\Doctrine'
                    is_bundle: false
