doctrine_mongodb:
    connections:
        default:
            server: '%env(resolve:MONGODB_URI)%'
    default_database: '%env(MONGODB_DB)%'
    document_managers:
        default:
            auto_mapping: false
