framework:
    messenger:
        buses:
            messenger.bus.default:
                middleware:
                    - App\Applications\Infrastructure\Messaging\AddEnrichmentHandlerArgumentsMiddleware
        failure_transport: failed
        transports:
            infrastructure_async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: infrastructure_probe
                        type: direct
                        default_publish_routing_key: infrastructure_probe
                    queues:
                        infrastructure_probe:
                            binding_keys: [infrastructure_probe]
                retry_strategy:
                    max_retries: 0
            enrichment_async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: application_enrichment
                        type: direct
                        default_publish_routing_key: application_enrichment
                    queues:
                        application_enrichment:
                            binding_keys: [application_enrichment]
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 4000
                    jitter: 0
            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: failed_messages
                        type: direct
                        default_publish_routing_key: failed_messages
                    queues:
                        failed_messages:
                            binding_keys: [failed_messages]
                retry_strategy:
                    max_retries: 0
        routing:
            App\Infrastructure\Probe\RabbitMq\InfrastructureProbeMessage: infrastructure_async
            App\Applications\Application\Command\EnrichApplication: enrichment_async

when@test:
    framework:
        messenger:
            transports:
                infrastructure_async: 'in-memory://'
                enrichment_async: 'in-memory://'
                failed: 'in-memory://'
